-----------------------------------------------------------
-- CREATE TABLES: Create tables for event management system
-----------------------------------------------------------

-- AUTHORS
-- Description: Author of a book
CREATE TABLE HAIRBD0028.AUTHORS
(
    AUTHOR_ID   NUMBER PRIMARY KEY,
    AUTHOR_NAME VARCHAR2(100) NOT NULL,
    NATIONALITY VARCHAR2(50)
);

-- BOOKS
-- Description: Book with its author
CREATE TABLE HAIRBD0028.BOOKS
(
    BOOK_ID          NUMBER PRIMARY KEY,
    TITLE            VARCHAR2(200) NOT NULL,
    GENRE            VARCHAR2(50),
    PUBLICATION_YEAR NUMBER(4),
    AUTHOR_ID        NUMBER,
    CONSTRAINT FK_BOOKS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES HAIRBD0028.AUTHORS (AUTHOR_ID)
);

-- MEMBERS (transaction time: manual)
-- Description: Member of the library
CREATE TABLE HAIRBD0028.MEMBERS
(
    MEMBER_ID   NUMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(100) UNIQUE,
    PHONE       VARCHAR2(20) UNIQUE,
    JOIN_DATE   DATE DEFAULT SYSDATE
);

-- BOOK_COPIES (transaction time: manual)
-- Description: Copies of a book
CREATE TABLE HAIRBD0028.BOOK_COPIES
(
    COPY_ID        NUMBER PRIMARY KEY,
    BOOK_ID        NUMBER NOT NULL,
    SHELF_LOCATION VARCHAR2(50),
    CONDITION_DESC VARCHAR2(100),
    CONSTRAINT FK_COPIES_BOOK FOREIGN KEY (BOOK_ID) REFERENCES HAIRBD0028.BOOKS (BOOK_ID)
);

-- LOANS (valid time via Oracle PERIOD)
-- Description: Loans of a book
CREATE TABLE HAIRBD0028.LOANS
(
    LOAN_ID     NUMBER PRIMARY KEY,
    MEMBER_ID   NUMBER NOT NULL,
    COPY_ID     NUMBER NOT NULL,
    VALID_START DATE   NOT NULL,
    VALID_END   DATE,
    STATUS      VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT CK_LOANS_VALID CHECK (VALID_END IS NULL OR VALID_END >= VALID_START),
    CONSTRAINT FK_LOANS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HAIRBD0028.MEMBERS (MEMBER_ID),
    CONSTRAINT FK_LOANS_COPY FOREIGN KEY (COPY_ID) REFERENCES HAIRBD0028.BOOK_COPIES (COPY_ID),
    PERIOD FOR VALID_TIME (VALID_START, VALID_END)
);

-- BOOK_COPIES HISTORY (transaction time audit)
-- Description: History of book copies
CREATE TABLE HAIRBD0028.BOOK_COPIES_HISTORY
(
    COPY_ID           NUMBER,
    BOOK_ID           NUMBER,
    SHELF_LOCATION    VARCHAR2(50),
    CONDITION_DESC    VARCHAR2(100),
    OPERATION_TYPE    VARCHAR2(10),
    TRANSACTION_START TIMESTAMP NOT NULL,
    TRANSACTION_END   TIMESTAMP,
    CONSTRAINT FK_BOOK_COPIES_HISTORY_BOOK FOREIGN KEY (BOOK_ID) REFERENCES HAIRBD0028.BOOKS (BOOK_ID)
);

-- LOANS HISTORY (transaction time audit)
-- Description: History of loans
CREATE TABLE HAIRBD0028.LOANS_HISTORY
(
    LOAN_ID           NUMBER,
    MEMBER_ID         NUMBER,
    COPY_ID           NUMBER,
    VALID_START       DATE,
    VALID_END         DATE,
    STATUS            VARCHAR2(20),
    OPERATION_TYPE    VARCHAR2(10),
    TRANSACTION_START TIMESTAMP NOT NULL,
    TRANSACTION_END   TIMESTAMP,
    CONSTRAINT FK_MEMBERS_HISTORY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES HAIRBD0028.MEMBERS (MEMBER_ID),
    CONSTRAINT FK_LOANS_HISTORY_COPY FOREIGN KEY (COPY_ID) REFERENCES HAIRBD0028.BOOK_COPIES (COPY_ID)
);

-----------------------------------------------------------
-- SELECT TABLES: Verify records in the created tables
-----------------------------------------------------------

SELECT * FROM HAIRBD0028.AUTHORS;
SELECT * FROM HAIRBD0028.BOOKS;
SELECT * FROM HAIRBD0028.MEMBERS;
SELECT * FROM HAIRBD0028.BOOK_COPIES;
SELECT * FROM HAIRBD0028.LOANS;
SELECT * FROM HAIRBD0028.LOANS_HISTORY;
SELECT * FROM HAIRBD0028.BOOK_COPIES_HISTORY;

-----------------------------------------------------------
-- DROP TABLES: Drop tables if they already exist
-----------------------------------------------------------

DROP TABLE HAIRBD0028.BOOK_COPIES_HISTORY CASCADE CONSTRAINTS;
DROP TABLE HAIRBD0028.LOANS_HISTORY CASCADE CONSTRAINTS;
DROP TABLE HAIRBD0028.LOANS CASCADE CONSTRAINTS;
DROP TABLE HAIRBD0028.BOOK_COPIES CASCADE CONSTRAINTS;
DROP TABLE HAIRBD0028.MEMBERS CASCADE CONSTRAINTS;
DROP TABLE HAIRBD0028.BOOKS CASCADE CONSTRAINTS;
DROP TABLE HAIRBD0028.AUTHORS CASCADE CONSTRAINTS;

-----------------------------------------------------------
-- DROP TRIGGERS: Drop triggers if they already exist
-----------------------------------------------------------

DROP TRIGGER HAIRBD0028.TRG_BOOK_COPIES_HISTORY;
DROP TRIGGER HAIRBD0028.TRG_LOANS_HISTORY;

-----------------------------------------------------------
-- DROP VIEWS: Drop views if they already exist
-----------------------------------------------------------

DROP VIEW HAIRBD0028.V_LOANS_CURRENT_VALID;
DROP VIEW HAIRBD0028.V_BOOK_COPIES_CHANGE_LOG;
DROP VIEW HAIRBD0028.V_LOANS_FIRST_RECORD;
DROP VIEW HAIRBD0028.V_LOANS_DATA_ENTRY;
DROP VIEW HAIRBD0028.V_LOANS_VALIDITY;
DROP VIEW HAIRBD0028.V_HISTORY_RECORDS;
