-----------------------------------------------------------
-- BOOK_COPIES audit trigger
-----------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_BOOK_COPIES_HISTORY
    AFTER INSERT OR UPDATE OR DELETE
    ON HAIRBD0028.BOOK_COPIES
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO HAIRBD0028.BOOK_COPIES_HISTORY (COPY_ID, BOOK_ID, SHELF_LOCATION, CONDITION_DESC, OPERATION_TYPE, TRANSACTION_START, TRANSACTION_END)
        VALUES (:NEW.COPY_ID, :NEW.BOOK_ID, :NEW.SHELF_LOCATION, :NEW.CONDITION_DESC, 'INSERT', SYSTIMESTAMP, NULL);

    ELSIF UPDATING THEN
        UPDATE HAIRBD0028.BOOK_COPIES_HISTORY SET TRANSACTION_END = SYSTIMESTAMP WHERE COPY_ID = :OLD.COPY_ID AND TRANSACTION_END IS NULL;

        INSERT INTO HAIRBD0028.BOOK_COPIES_HISTORY (COPY_ID, BOOK_ID, SHELF_LOCATION, CONDITION_DESC, OPERATION_TYPE, TRANSACTION_START, TRANSACTION_END)
        VALUES (:NEW.COPY_ID, :NEW.BOOK_ID, :NEW.SHELF_LOCATION, :NEW.CONDITION_DESC, 'UPDATE', SYSTIMESTAMP, NULL);

    ELSIF DELETING THEN
        UPDATE HAIRBD0028.BOOK_COPIES_HISTORY SET TRANSACTION_END = SYSTIMESTAMP WHERE COPY_ID = :OLD.COPY_ID AND TRANSACTION_END IS NULL;

        INSERT INTO HAIRBD0028.BOOK_COPIES_HISTORY (COPY_ID, BOOK_ID, SHELF_LOCATION, CONDITION_DESC, OPERATION_TYPE, TRANSACTION_START, TRANSACTION_END)
        VALUES (:OLD.COPY_ID, :OLD.BOOK_ID, :OLD.SHELF_LOCATION, :OLD.CONDITION_DESC, 'DELETE', SYSTIMESTAMP, SYSTIMESTAMP);
    END IF;
END;

-----------------------------------------------------------
-- LOANS audit trigger
-----------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_LOANS_HISTORY
    AFTER INSERT OR UPDATE OR DELETE
    ON HAIRBD0028.LOANS
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO HAIRBD0028.LOANS_HISTORY (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS, OPERATION_TYPE, TRANSACTION_START, TRANSACTION_END)
        VALUES (:NEW.LOAN_ID, :NEW.MEMBER_ID, :NEW.COPY_ID, :NEW.VALID_START, :NEW.VALID_END, :NEW.STATUS, 'INSERT', SYSTIMESTAMP, NULL);

    ELSIF UPDATING THEN
        UPDATE HAIRBD0028.LOANS_HISTORY SET TRANSACTION_END = SYSTIMESTAMP WHERE LOAN_ID = :OLD.LOAN_ID AND TRANSACTION_END IS NULL;

        INSERT INTO HAIRBD0028.LOANS_HISTORY (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS, OPERATION_TYPE, TRANSACTION_START, TRANSACTION_END)
        VALUES (:NEW.LOAN_ID, :NEW.MEMBER_ID, :NEW.COPY_ID, :NEW.VALID_START, :NEW.VALID_END, :NEW.STATUS, 'UPDATE', SYSTIMESTAMP, NULL);

    ELSIF DELETING THEN
        UPDATE HAIRBD0028.LOANS_HISTORY SET TRANSACTION_END = SYSTIMESTAMP WHERE LOAN_ID = :OLD.LOAN_ID AND TRANSACTION_END IS NULL;

        INSERT INTO HAIRBD0028.LOANS_HISTORY (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS, OPERATION_TYPE, TRANSACTION_START, TRANSACTION_END)
        VALUES (:OLD.LOAN_ID, :OLD.MEMBER_ID, :OLD.COPY_ID, :OLD.VALID_START, :OLD.VALID_END, :OLD.STATUS, 'DELETE', SYSTIMESTAMP, SYSTIMESTAMP);
    END IF;
END;

-----------------------------------------------------------
-- VERIFY TRIGGERS: Test triggers by performing DML operations
-----------------------------------------------------------

INSERT INTO HAIRBD0028.BOOK_COPIES (COPY_ID, BOOK_ID, SHELF_LOCATION, CONDITION_DESC) VALUES (23, 1, 'A1-S1', 'NEW');
UPDATE HAIRBD0028.BOOK_COPIES SET CONDITION_DESC = 'FAIR' WHERE COPY_ID = 23;
DELETE FROM HAIRBD0028.BOOK_COPIES WHERE COPY_ID = 23;
SELECT * FROM HAIRBD0028.BOOK_COPIES ORDER BY COPY_ID DESC;
SELECT * FROM HAIRBD0028.BOOK_COPIES_HISTORY ORDER BY TRANSACTION_START DESC;
COMMIT;

INSERT INTO HAIRBD0028.LOANS (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, STATUS) VALUES (81, 29, 2, TO_DATE('2025-01-01 12:24:48', 'YYYY-MM-DD HH24:MI:SS'), 'ACTIVE');
UPDATE HAIRBD0028.LOANS SET STATUS = 'RETURNED', VALID_END = SYSDATE WHERE LOAN_ID = 81;
DELETE FROM HAIRBD0028.LOANS WHERE LOAN_ID = 81;
SELECT * FROM HAIRBD0028.LOANS ORDER BY LOAN_ID DESC;
SELECT * FROM HAIRBD0028.LOANS_HISTORY ORDER BY TRANSACTION_START DESC;
COMMIT;

-----------------------------------------------------------
-- INSERT SAMPLE DATA INTO LOANS TABLE
-----------------------------------------------------------

INSERT INTO HAIRBD0028.LOANS (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS) VALUES (76, 29, 19, TO_DATE('2025-10-27 16:01:02', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'ACTIVE');
INSERT INTO HAIRBD0028.LOANS (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS) VALUES (77, 2, 12, TO_DATE('2025-10-27 16:01:02', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'ACTIVE');
INSERT INTO HAIRBD0028.LOANS (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS) VALUES (78, 9, 9, TO_DATE('2025-10-28 16:01:02', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'PENDING');
INSERT INTO HAIRBD0028.LOANS (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS) VALUES (79, 29, 9, TO_DATE('2025-10-29 10:01:02', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'PENDING');
INSERT INTO HAIRBD0028.LOANS (LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, VALID_END, STATUS) VALUES (80, 2, 1, TO_DATE('2025-10-28 16:01:02', 'YYYY-MM-DD HH24:MI:SS'), NULL, 'ACTIVE');
COMMIT;