/*CREATE DATABASE library;*/
USE library;

DROP TABLE IF EXISTS LOANS;
DROP TABLE IF EXISTS BOOK_COPIES;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS
(
    AUTHOR_ID   INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(100) NOT NULL,
    NATIONALITY VARCHAR(50)
);

CREATE TABLE BOOKS
(
    BOOK_ID   INT PRIMARY KEY,
    TITLE     VARCHAR(200) NOT NULL,
    GENRE     VARCHAR(50),
    PUBLICATION_YEAR YEAR,
    AUTHOR_ID INT,
    CONSTRAINT FK_BOOKS_AUTHOR
        FOREIGN KEY (AUTHOR_ID)
            REFERENCES AUTHORS (AUTHOR_ID)
            ON DELETE SET NULL
);

CREATE TABLE MEMBERS
(
    MEMBER_ID   INT PRIMARY KEY,
    MEMBER_NAME VARCHAR(100) NOT NULL,
    EMAIL       VARCHAR(100) UNIQUE,
    PHONE       VARCHAR(20) UNIQUE,
    JOIN_DATE   DATE DEFAULT (CURRENT_DATE)
);

CREATE TABLE BOOK_COPIES
(
    COPY_ID        INT PRIMARY KEY,
    BOOK_ID        INT NOT NULL,
    SHELF_LOCATION VARCHAR(50),
    CONDITION_DESC VARCHAR(100),
    CONSTRAINT FK_COPIES_BOOK
        FOREIGN KEY (BOOK_ID)
            REFERENCES BOOKS (BOOK_ID)
            ON DELETE CASCADE
);

CREATE TABLE LOANS
(
    LOAN_ID     INT PRIMARY KEY,
    MEMBER_ID   INT  NOT NULL,
    COPY_ID     INT  NOT NULL,
    VALID_START DATE NOT NULL,
    VALID_END   DATE,
    STATUS      VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT CK_LOANS_VALID
        CHECK (VALID_END IS NULL OR VALID_END >= VALID_START),
    CONSTRAINT FK_LOANS_MEMBER
        FOREIGN KEY (MEMBER_ID)
            REFERENCES MEMBERS (MEMBER_ID)
            ON DELETE CASCADE,
    CONSTRAINT FK_LOANS_COPY
        FOREIGN KEY (COPY_ID)
            REFERENCES BOOK_COPIES (COPY_ID)
            ON DELETE CASCADE
);