CREATE TABLE authors
(
    "AUTHOR_ID"   INTEGER PRIMARY KEY,
    "AUTHOR_NAME" VARCHAR(100) NOT NULL,
    "NATIONALITY" VARCHAR(50)
);

CREATE TABLE books
(
    "BOOK_ID"          INTEGER PRIMARY KEY,
    "TITLE"            VARCHAR(200) NOT NULL,
    "GENRE"            VARCHAR(50),
    "PUBLICATION_YEAR" INTEGER,
    "AUTHOR_ID"        INTEGER REFERENCES authors ("AUTHOR_ID")
);

CREATE TABLE members
(
    "MEMBER_ID"   INTEGER PRIMARY KEY,
    "MEMBER_NAME" VARCHAR(100) NOT NULL,
    "EMAIL"       VARCHAR(100) UNIQUE,
    "PHONE"       VARCHAR(20) UNIQUE,
    "JOIN_DATE"   DATE DEFAULT CURRENT_DATE
);

CREATE TABLE book_copies
(
    "COPY_ID"        INTEGER PRIMARY KEY,
    "BOOK_ID"        INTEGER NOT NULL REFERENCES books ("BOOK_ID"),
    "SHELF_LOCATION" VARCHAR(50),
    "CONDITION_DESC" VARCHAR(100)
);

CREATE TABLE loans
(
    "LOAN_ID"     INTEGER PRIMARY KEY,
    "MEMBER_ID"   INTEGER NOT NULL REFERENCES members ("MEMBER_ID"),
    "COPY_ID"     INTEGER NOT NULL REFERENCES book_copies ("COPY_ID"),
    "VALID_START" DATE    NOT NULL,
    "VALID_END"   DATE,
    "STATUS"      VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT ck_loans_valid CHECK ("VALID_END" IS NULL OR "VALID_END" >= "VALID_START")
);