USE library;

DELETE FROM LOANS;
DELETE FROM BOOK_COPIES;
DELETE FROM BOOKS;
DELETE FROM MEMBERS;
DELETE FROM AUTHORS;

COMMIT;

INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, NATIONALITY)
VALUES (1, 'George Orwell', 'British');

INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME, NATIONALITY)
VALUES (2, 'Jules Verne', 'French');

INSERT INTO BOOKS
(BOOK_ID, TITLE, GENRE, PUBLICATION_YEAR, AUTHOR_ID)
VALUES (10, '1984', 'Dystopian', 1949, 1);

INSERT INTO BOOKS
(BOOK_ID, TITLE, GENRE, PUBLICATION_YEAR, AUTHOR_ID)
VALUES (11, 'Journey to the Center of the Earth', 'Science Fiction', 1864, 2);

INSERT INTO MEMBERS
(MEMBER_ID, MEMBER_NAME, EMAIL, PHONE, JOIN_DATE)
VALUES (100, 'Ana Popescu', 'ana@email.com', '0712345678', NOW());

INSERT INTO MEMBERS
(MEMBER_ID, MEMBER_NAME, EMAIL, PHONE, JOIN_DATE)
VALUES (101, 'Ion Ionescu', 'ion@email.com', '0722334455', NOW());

INSERT INTO BOOK_COPIES
(COPY_ID, BOOK_ID, SHELF_LOCATION, CONDITION_DESC)
VALUES (1000, 10, 'A3', 'Good');

INSERT INTO BOOK_COPIES
(COPY_ID, BOOK_ID, SHELF_LOCATION, CONDITION_DESC)
VALUES (1001, 11, 'B1', 'Excellent');

INSERT INTO LOANS
(LOAN_ID, MEMBER_ID, COPY_ID, VALID_START, STATUS)
VALUES (5000, 100, 1000, NOW(), 'ACTIVE');

COMMIT;

SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;
SELECT * FROM MEMBERS;
SELECT * FROM BOOK_COPIES;
SELECT * FROM LOANS;

UPDATE AUTHORS SET AUTHOR_NAME = 'G. Orwell', NATIONALITY = 'UK' WHERE AUTHOR_ID = 1;
UPDATE BOOKS SET GENRE = 'Political Fiction' WHERE BOOK_ID = 10;
UPDATE MEMBERS SET EMAIL = 'ana.popescu@email.com' WHERE MEMBER_ID = 100;
UPDATE BOOK_COPIES SET SHELF_LOCATION = 'C2' WHERE COPY_ID = 1000;
UPDATE LOANS SET VALID_END = NOW(), STATUS = 'RETURNED' WHERE LOAN_ID = 5000;

COMMIT;

DELETE FROM LOANS WHERE LOAN_ID = 5000;
DELETE FROM BOOK_COPIES WHERE COPY_ID = 1000;
DELETE FROM BOOKS WHERE BOOK_ID = 10;
DELETE FROM MEMBERS WHERE MEMBER_ID = 100;
DELETE FROM AUTHORS WHERE AUTHOR_ID = 1;

COMMIT;