DROP TABLE HAIRBD0028.PRODUSE CASCADE CONSTRAINTS PURGE;
CREATE TABLE HAIRBD0028.PRODUSE
(
    COD      NUMBER,
    DENUMIRE VARCHAR2(150)
);

DROP TABLE HAIRBD0028.STRUCTURA CASCADE CONSTRAINTS PURGE;
CREATE TABLE structura
(
    COD     NUMBER,
    CODP    NUMBER,
    POZITIA NUMBER
);