-- All tables owned by the current user.
-- This view does not display the OWNER column. (current schema)
SELECT * FROM USER_TABLES;

-- All tables accessible to the current user. (all schemas)
SELECT * FROM ALL_TABLES;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'BOOKS';
SELECT TABLE_NAME, INDEX_NAME, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'BOOKS';
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BOOKS';

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MEMBERS';
SELECT TABLE_NAME, INDEX_NAME, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'MEMBERS';
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEMBERS';

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'LOANS';
SELECT TABLE_NAME, INDEX_NAME, UNIQUENESS FROM USER_INDEXES WHERE TABLE_NAME = 'LOANS';
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOANS';