CREATE OR REPLACE VIEW VIEW_AVAILABLE_PROCEDURES AS
SELECT OWNER AS schema_name, OBJECT_NAME AS procedure_name
FROM ALL_PROCEDURES WHERE OBJECT_TYPE = 'PROCEDURE';

SELECT * FROM VIEW_AVAILABLE_PROCEDURES;