CREATE TABLE "STUDENTI" 
   (	"NUME" CHAR(30 BYTE), 
	"PRENUME" CHAR(30 BYTE), 
	"COD_SECTIA" NUMBER(3,0), 
	"DENUMIRE_SECTIA" VARCHAR2(70 BYTE), 
	"AN_STUDIU" NUMBER(1,0), 
	"GRUPA" CHAR(10 BYTE), 
	"MEDIA" NUMBER(5,2)
   ) ;

Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 1','Prenume 1','22','Informatica - în limba engleza','1','911       ','5,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 2','Prenume 2','22','Informatica - în limba engleza','1','912       ','8,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 3','Prenume 3','22','Informatica - în limba engleza','1','912       ','7,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 4','Prenume 4','22','Informatica - în limba engleza','1','912       ','8,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 5','Prenume 5','2','Informatica - linia de studiu romana','1','215       ','6,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 6','Prenume 6','2','Informatica - linia de studiu romana','1','216       ','9,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 7','Prenume 7','22','Informatica - în limba engleza','3','933       ','6,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 8','Prenume 8','22','Informatica - în limba engleza','3','933       ','9,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 9','Prenume 9','22','Informatica - în limba engleza','3','933       ','6,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 10','Prenume 10','22','Informatica - în limba engleza','3','932       ','9,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 11','Prenume 11','22','Informatica - în limba engleza','2','921       ','9,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 12','Prenume 12','22','Informatica - în limba engleza','2','922       ','7,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 13','Prenume 13','11','Matematica - linia de studiu maghiara','1','411       ','7,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 14','Prenume 14','22','Informatica - în limba engleza','1','913       ','7,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 15','Prenume 15','22','Informatica - în limba engleza','1','914       ','8,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 16','Prenume 16','12','Informatica - linia de studiu maghiara','1','511       ','5,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 17','Prenume 17','2','Informatica - linia de studiu romana','4','242       ','7,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 18','Prenume 18','3','Matematica-Informatica - linia de studiu romana','4','342       ','5,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 19','Prenume 19','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 20','Prenume 20','2','Informatica - linia de studiu romana','3','232       ','5,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 21','Prenume 21','3','Matematica-Informatica - linia de studiu romana','3','331       ','5,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 22','Prenume 22','3','Matematica-Informatica - linia de studiu romana','3','331       ','6,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 23','Prenume 23','22','Informatica - în limba engleza','2','923       ','8,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 24','Prenume 24','22','Informatica - în limba engleza','2','923       ','8,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 25','Prenume 25','2','Informatica - linia de studiu romana','3','233       ','9,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 26','Prenume 26','2','Informatica - linia de studiu romana','3','233       ','6,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 27','Prenume 27','22','Informatica - în limba engleza','2','922       ','7,12');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 28','Prenume 28','12','Informatica - linia de studiu maghiara','2','521       ','8,16');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 29','Prenume 29','12','Informatica - linia de studiu maghiara','2','521       ','8,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 30','Prenume 30','12','Informatica - linia de studiu maghiara','2','521       ','6,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 31','Prenume 31','12','Informatica - linia de studiu maghiara','2','521       ','5,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 32','Prenume 32','12','Informatica - linia de studiu maghiara','1','511       ','9,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 33','Prenume 33','2','Informatica - linia de studiu romana','1','211       ','9,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 34','Prenume 34','2','Informatica - linia de studiu romana','1','212       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 35','Prenume 35','2','Informatica - linia de studiu romana','1','212       ','8,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 36','Prenume 36','3','Matematica-Informatica - linia de studiu romana','1','311       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 37','Prenume 37','3','Matematica-Informatica - linia de studiu romana','1','311       ','9,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 38','Prenume 38','2','Informatica - linia de studiu romana','3','231       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 39','Prenume 39','2','Informatica - linia de studiu romana','3','232       ','5,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 40','Prenume 40','22','Informatica - în limba engleza','1','914       ','5,86');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 41','Prenume 41','22','Informatica - în limba engleza','1','914       ','6,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 42','Prenume 42','22','Informatica - în limba engleza','1','914       ','5,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 43','Prenume 43','22','Informatica - în limba engleza','1','915       ','6,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 44','Prenume 44','22','Informatica - în limba engleza','2','923       ','9,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 45','Prenume 45','2','Informatica - linia de studiu romana','4','243       ','8,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 46','Prenume 46','22','Informatica - în limba engleza','1','915       ','5,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 47','Prenume 47','1','Matematica - linia de studiu romana','3','131       ','5,78');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 48','Prenume 48','2','Informatica - linia de studiu romana','2','224       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 49','Prenume 49','3','Matematica-Informatica - linia de studiu romana','2','321       ','7,82');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 50','Prenume 50','3','Matematica-Informatica - linia de studiu romana','2','321       ','5,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 51','Prenume 51','2','Informatica - linia de studiu romana','2','223       ','5,27');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 52','Prenume 52','2','Informatica - linia de studiu romana','4','242       ','7,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 53','Prenume 53','2','Informatica - linia de studiu romana','2','221       ','8,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 54','Prenume 54','22','Informatica - în limba engleza','2','922       ','8,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 55','Prenume 55','2','Informatica - linia de studiu romana','3','231       ','7,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 56','Prenume 56','2','Informatica - linia de studiu romana','2','224       ','9,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 57','Prenume 57','22','Informatica - în limba engleza','2','923       ','9,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 58','Prenume 58','2','Informatica - linia de studiu romana','1','218       ','9,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 59','Prenume 59','2','Informatica - linia de studiu romana','4','241       ','6,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 60','Prenume 60','22','Informatica - în limba engleza','4','941       ','5,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 61','Prenume 61','22','Informatica - în limba engleza','4','941       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 62','Prenume 62','22','Informatica - în limba engleza','4','943       ','7,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 63','Prenume 63','22','Informatica - în limba engleza','4','943       ','9,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 64','Prenume 64','22','Informatica - în limba engleza','4','943       ','6,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 65','Prenume 65','22','Informatica - în limba engleza','3','931       ','6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 66','Prenume 66','22','Informatica - în limba engleza','2','921       ','7,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 67','Prenume 67','22','Informatica - în limba engleza','1','911       ','6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 68','Prenume 68','22','Informatica - în limba engleza','1','912       ','6,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 69','Prenume 69','22','Informatica - în limba engleza','1','912       ','8,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 70','Prenume 70','2','Informatica - linia de studiu romana','1','213       ','8,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 71','Prenume 71','2','Informatica - linia de studiu romana','1','213       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 72','Prenume 72','2','Informatica - linia de studiu romana','1','214       ','9,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 73','Prenume 73','2','Informatica - linia de studiu romana','1','216       ','6,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 74','Prenume 74','22','Informatica - în limba engleza','3','933       ','6,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 75','Prenume 75','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 76','Prenume 76','3','Matematica-Informatica - linia de studiu romana','3','332       ','8,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 77','Prenume 77','22','Informatica - în limba engleza','1','913       ','6,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 78','Prenume 78','22','Informatica - în limba engleza','1','913       ','9,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 79','Prenume 79','22','Informatica - în limba engleza','1','913       ','9,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 80','Prenume 80','12','Informatica - linia de studiu maghiara','1','511       ','7,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 81','Prenume 81','12','Informatica - linia de studiu maghiara','1','512       ','6,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 82','Prenume 82','12','Informatica - linia de studiu maghiara','1','512       ','7,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 83','Prenume 83','12','Informatica - linia de studiu maghiara','1','512       ','5,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 84','Prenume 84','12','Informatica - linia de studiu maghiara','1','513       ','7,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 85','Prenume 85','12','Informatica - linia de studiu maghiara','4','541       ','9,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 86','Prenume 86','12','Informatica - linia de studiu maghiara','4','541       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 87','Prenume 87','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 88','Prenume 88','22','Informatica - în limba engleza','1','913       ','8,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 89','Prenume 89','22','Informatica - în limba engleza','1','913       ','5,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 90','Prenume 90','22','Informatica - în limba engleza','2','923       ','5,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 91','Prenume 91','22','Informatica - în limba engleza','2','923       ','8,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 92','Prenume 92','2','Informatica - linia de studiu romana','3','233       ','9,98');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 93','Prenume 93','12','Informatica - linia de studiu maghiara','3','531       ','8,07');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 94','Prenume 94','12','Informatica - linia de studiu maghiara','3','531       ','5,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 95','Prenume 95','2','Informatica - linia de studiu romana','1','211       ','7,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 96','Prenume 96','2','Informatica - linia de studiu romana','1','212       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 97','Prenume 97','3','Matematica-Informatica - linia de studiu romana','1','311       ','8,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 98','Prenume 98','3','Matematica-Informatica - linia de studiu romana','1','311       ','7,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 99','Prenume 99','2','Informatica - linia de studiu romana','3','231       ','6,27');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 100','Prenume 100','22','Informatica - în limba engleza','1','914       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 101','Prenume 101','22','Informatica - în limba engleza','1','915       ','9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 102','Prenume 102','2','Informatica - linia de studiu romana','4','241       ','7,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 103','Prenume 103','2','Informatica - linia de studiu romana','4','244       ','5,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 104','Prenume 104','22','Informatica - în limba engleza','2','921       ','9,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 105','Prenume 105','2','Informatica - linia de studiu romana','4','244       ','6,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 106','Prenume 106','2','Informatica - linia de studiu romana','2','224       ','9,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 107','Prenume 107','22','Informatica - în limba engleza','2','921       ','5,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 108','Prenume 108','2','Informatica - linia de studiu romana','2','222       ','5,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 109','Prenume 109','22','Informatica - în limba engleza','3','931       ','7,42');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 110','Prenume 110','22','Informatica - în limba engleza','1','911       ','7,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 111','Prenume 111','22','Informatica - în limba engleza','2','921       ','6,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 112','Prenume 112','2','Informatica - linia de studiu romana','1','213       ','6,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 113','Prenume 113','2','Informatica - linia de studiu romana','1','216       ','6,98');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 114','Prenume 114','2','Informatica - linia de studiu romana','1','217       ','7,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 115','Prenume 115','22','Informatica - în limba engleza','3','932       ','7,72');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 116','Prenume 116','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 117','Prenume 117','3','Matematica-Informatica - linia de studiu romana','3','332       ','5,96');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 118','Prenume 118','21','Matematica-Informatica -linia de studiu germana','4','741       ','8,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 119','Prenume 119','22','Informatica - în limba engleza','1','913       ','5,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 120','Prenume 120','22','Informatica - în limba engleza','1','914       ','6,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 121','Prenume 121','12','Informatica - linia de studiu maghiara','1','511       ','8,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 122','Prenume 122','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 123','Prenume 123','2','Informatica - linia de studiu romana','3','232       ','6,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 124','Prenume 124','3','Matematica-Informatica - linia de studiu romana','3','332       ','6,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 125','Prenume 125','22','Informatica - în limba engleza','2','923       ','9,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 126','Prenume 126','22','Informatica - în limba engleza','2','923       ','8,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 127','Prenume 127','22','Informatica - în limba engleza','2','923       ','7,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 128','Prenume 128','2','Informatica - linia de studiu romana','3','232       ','5,48');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 129','Prenume 129','2','Informatica - linia de studiu romana','3','233       ','8,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 130','Prenume 130','2','Informatica - linia de studiu romana','3','233       ','5,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 131','Prenume 131','2','Informatica - linia de studiu romana','3','233       ','9,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 132','Prenume 132','2','Informatica - linia de studiu romana','1','212       ','5,9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 133','Prenume 133','2','Informatica - linia de studiu romana','1','212       ','6,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 134','Prenume 134','22','Informatica - în limba engleza','1','914       ','5,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 135','Prenume 135','1','Matematica - linia de studiu romana','1','111       ','6,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 136','Prenume 136','1','Matematica - linia de studiu romana','1','111       ','8,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 137','Prenume 137','2','Informatica - linia de studiu romana','4','241       ','7,07');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 138','Prenume 138','22','Informatica - în limba engleza','1','915       ','6,09');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 139','Prenume 139','22','Informatica - în limba engleza','1','915       ','8,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 140','Prenume 140','22','Informatica - în limba engleza','2','921       ','6,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 141','Prenume 141','2','Informatica - linia de studiu romana','4','244       ','5,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 142','Prenume 142','1','Matematica - linia de studiu romana','4','141       ','5,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 143','Prenume 143','1','Matematica - linia de studiu romana','3','131       ','5,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 144','Prenume 144','2','Informatica - linia de studiu romana','4','244       ','7,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 145','Prenume 145','22','Informatica - în limba engleza','3','932       ','7,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 146','Prenume 146','22','Informatica - în limba engleza','2','922       ','5,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 147','Prenume 147','2','Informatica - linia de studiu romana','1','218       ','9,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 148','Prenume 148','43','Baze de date','1','253       ','9,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 149','Prenume 149','22','Informatica - în limba engleza','2','921       ','8,96');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 150','Prenume 150','2','Informatica - linia de studiu romana','2','221       ','7,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 151','Prenume 151','2','Informatica - linia de studiu romana','2','221       ','9,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 152','Prenume 152','2','Informatica - linia de studiu romana','2','221       ','7,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 153','Prenume 153','2','Informatica - linia de studiu romana','2','223       ','6,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 154','Prenume 154','2','Informatica - linia de studiu romana','1','217       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 155','Prenume 155','2','Informatica - linia de studiu romana','3','233       ','7,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 156','Prenume 156','2','Informatica - linia de studiu romana','2','221       ','8,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 157','Prenume 157','22','Informatica - în limba engleza','4','941       ','5,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 158','Prenume 158','22','Informatica - în limba engleza','4','943       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 159','Prenume 159','22','Informatica - în limba engleza','4','943       ','9,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 160','Prenume 160','22','Informatica - în limba engleza','4','942       ','5,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 161','Prenume 161','22','Informatica - în limba engleza','4','942       ','5,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 162','Prenume 162','2','Informatica - linia de studiu romana','4','241       ','5,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 163','Prenume 163','12','Informatica - linia de studiu maghiara','2','521       ','6,79');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 164','Prenume 164','22','Informatica - în limba engleza','3','932       ','8,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 165','Prenume 165','22','Informatica - în limba engleza','1','911       ','7,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 166','Prenume 166','22','Informatica - în limba engleza','1','912       ','8,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 167','Prenume 167','22','Informatica - în limba engleza','1','912       ','9,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 168','Prenume 168','22','Informatica - în limba engleza','1','912       ','9,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 169','Prenume 169','2','Informatica - linia de studiu romana','1','213       ','8,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 170','Prenume 170','2','Informatica - linia de studiu romana','1','214       ','6,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 171','Prenume 171','2','Informatica - linia de studiu romana','1','214       ','6,48');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 172','Prenume 172','2','Informatica - linia de studiu romana','1','215       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 173','Prenume 173','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 174','Prenume 174','3','Matematica-Informatica - linia de studiu romana','4','342       ','5,49');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 175','Prenume 175','3','Matematica-Informatica - linia de studiu romana','4','342       ','9,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 176','Prenume 176','3','Matematica-Informatica - linia de studiu romana','3','332       ','5,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 177','Prenume 177','22','Informatica - în limba engleza','1','914       ','5,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 178','Prenume 178','12','Informatica - linia de studiu maghiara','1','512       ','6,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 179','Prenume 179','2','Informatica - linia de studiu romana','4','243       ','5,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 180','Prenume 180','2','Informatica - linia de studiu romana','4','242       ','8,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 181','Prenume 181','12','Informatica - linia de studiu maghiara','3','531       ','6,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 182','Prenume 182','2','Informatica - linia de studiu romana','4','242       ','6,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 183','Prenume 183','22','Informatica - în limba engleza','1','913       ','7,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 184','Prenume 184','22','Informatica - în limba engleza','2','923       ','5,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 185','Prenume 185','22','Informatica - în limba engleza','2','923       ','8,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 186','Prenume 186','2','Informatica - linia de studiu romana','3','233       ','7,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 187','Prenume 187','12','Informatica - linia de studiu maghiara','3','531       ','9,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 188','Prenume 188','12','Informatica - linia de studiu maghiara','2','521       ','6,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 189','Prenume 189','2','Informatica - linia de studiu romana','1','211       ','7,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 190','Prenume 190','2','Informatica - linia de studiu romana','1','214       ','6,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 191','Prenume 191','2','Informatica - linia de studiu romana','2','223       ','9,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 192','Prenume 192','2','Informatica - linia de studiu romana','3','231       ','7,43');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 193','Prenume 193','2','Informatica - linia de studiu romana','2','221       ','6,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 194','Prenume 194','22','Informatica - în limba engleza','1','914       ','5,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 195','Prenume 195','1','Matematica - linia de studiu romana','1','111       ','5,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 196','Prenume 196','22','Informatica - în limba engleza','1','915       ','7,64');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 197','Prenume 197','1','Matematica - linia de studiu romana','2','121       ','8,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 198','Prenume 198','2','Informatica - linia de studiu romana','1','218       ','5,13');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 199','Prenume 199','2','Informatica - linia de studiu romana','2','224       ','6,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 200','Prenume 200','22','Informatica - în limba engleza','2','921       ','5,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 201','Prenume 201','3','Matematica-Informatica - linia de studiu romana','2','321       ','7,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 202','Prenume 202','2','Informatica - linia de studiu romana','2','223       ','6,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 203','Prenume 203','2','Informatica - linia de studiu romana','4','243       ','5,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 204','Prenume 204','2','Informatica - linia de studiu romana','2','221       ','8,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 205','Prenume 205','41','Programare bazata pe componente (în limba engleza)','1','251       ','8,09');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 206','Prenume 206','43','Baze de date','1','253       ','9,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 207','Prenume 207','2','Informatica - linia de studiu romana','1','217       ','7,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 208','Prenume 208','2','Informatica - linia de studiu romana','2','224       ','6,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 209','Prenume 209','2','Informatica - linia de studiu romana','1','218       ','9,79');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 210','Prenume 210','22','Informatica - în limba engleza','4','943       ','7,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 211','Prenume 211','22','Informatica - în limba engleza','4','943       ','6,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 212','Prenume 212','22','Informatica - în limba engleza','4','942       ','6,89');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 213','Prenume 213','12','Informatica - linia de studiu maghiara','2','521       ','9,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 214','Prenume 214','2','Informatica - linia de studiu romana','4','243       ','7,5');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 215','Prenume 215','22','Informatica - în limba engleza','1','911       ','5,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 216','Prenume 216','22','Informatica - în limba engleza','1','911       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 217','Prenume 217','22','Informatica - în limba engleza','1','912       ','7,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 218','Prenume 218','22','Informatica - în limba engleza','1','912       ','5,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 219','Prenume 219','22','Informatica - în limba engleza','1','912       ','5,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 220','Prenume 220','22','Informatica - în limba engleza','1','912       ','5,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 221','Prenume 221','22','Informatica - în limba engleza','1','912       ','9,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 222','Prenume 222','22','Informatica - în limba engleza','1','912       ','9,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 223','Prenume 223','13','Matematica-Informatica - linia de studiu maghiara','4','641       ','6,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 224','Prenume 224','2','Informatica - linia de studiu romana','1','216       ','9,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 225','Prenume 225','22','Informatica - în limba engleza','3','933       ','6,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 226','Prenume 226','22','Informatica - în limba engleza','3','933       ','6,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 227','Prenume 227','22','Informatica - în limba engleza','3','933       ','8,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 228','Prenume 228','22','Informatica - în limba engleza','3','932       ','7,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 229','Prenume 229','22','Informatica - în limba engleza','2','921       ','5,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 230','Prenume 230','3','Matematica-Informatica - linia de studiu romana','3','332       ','6,75');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 231','Prenume 231','12','Informatica - linia de studiu maghiara','1','511       ','6,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 232','Prenume 232','12','Informatica - linia de studiu maghiara','1','511       ','7,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 233','Prenume 233','12','Informatica - linia de studiu maghiara','1','512       ','7,75');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 234','Prenume 234','12','Informatica - linia de studiu maghiara','1','512       ','5,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 235','Prenume 235','12','Informatica - linia de studiu maghiara','1','512       ','6,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 236','Prenume 236','2','Informatica - linia de studiu romana','4','242       ','9,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 237','Prenume 237','22','Informatica - în limba engleza','2','923       ','6,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 238','Prenume 238','22','Informatica - în limba engleza','2','923       ','5,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 239','Prenume 239','12','Informatica - linia de studiu maghiara','3','531       ','7,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 240','Prenume 240','12','Informatica - linia de studiu maghiara','3','531       ','8,67');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 241','Prenume 241','12','Informatica - linia de studiu maghiara','3','531       ','9,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 242','Prenume 242','12','Informatica - linia de studiu maghiara','2','521       ','5,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 243','Prenume 243','2','Informatica - linia de studiu romana','1','211       ','8,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 244','Prenume 244','2','Informatica - linia de studiu romana','1','212       ','7,28');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 245','Prenume 245','3','Matematica-Informatica - linia de studiu romana','1','311       ','9,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 246','Prenume 246','2','Informatica - linia de studiu romana','3','231       ','5,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 247','Prenume 247','2','Informatica - linia de studiu romana','3','231       ','6,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 248','Prenume 248','22','Informatica - în limba engleza','1','914       ','8,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 249','Prenume 249','22','Informatica - în limba engleza','1','914       ','6,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 250','Prenume 250','1','Matematica - linia de studiu romana','1','111       ','5,85');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 251','Prenume 251','1','Matematica - linia de studiu romana','1','111       ','8,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 252','Prenume 252','22','Informatica - în limba engleza','1','915       ','8,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 253','Prenume 253','22','Informatica - în limba engleza','1','915       ','9,49');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 254','Prenume 254','22','Informatica - în limba engleza','1','915       ','8,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 255','Prenume 255','22','Informatica - în limba engleza','2','921       ','5,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 256','Prenume 256','2','Informatica - linia de studiu romana','2','223       ','8,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 257','Prenume 257','2','Informatica - linia de studiu romana','2','223       ','8,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 258','Prenume 258','2','Informatica - linia de studiu romana','2','221       ','9,09');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 259','Prenume 259','2','Informatica - linia de studiu romana','2','221       ','6,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 260','Prenume 260','2','Informatica - linia de studiu romana','1','217       ','8,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 261','Prenume 261','2','Informatica - linia de studiu romana','1','217       ','6,13');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 262','Prenume 262','2','Informatica - linia de studiu romana','4','243       ','8,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 263','Prenume 263','2','Informatica - linia de studiu romana','1','218       ','9,18');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 264','Prenume 264','22','Informatica - în limba engleza','4','941       ','7,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 265','Prenume 265','22','Informatica - în limba engleza','4','942       ','8,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 266','Prenume 266','2','Informatica - linia de studiu romana','4','242       ','7,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 267','Prenume 267','22','Informatica - în limba engleza','3','931       ','6,18');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 268','Prenume 268','22','Informatica - în limba engleza','3','932       ','5,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 269','Prenume 269','22','Informatica - în limba engleza','2','921       ','7,72');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 270','Prenume 270','22','Informatica - în limba engleza','1','911       ','7,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 271','Prenume 271','2','Informatica - linia de studiu romana','2','222       ','7,9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 272','Prenume 272','2','Informatica - linia de studiu romana','2','222       ','7,42');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 273','Prenume 273','2','Informatica - linia de studiu romana','2','222       ','6,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 274','Prenume 274','2','Informatica - linia de studiu romana','2','222       ','9,22');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 275','Prenume 275','22','Informatica - în limba engleza','2','922       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 276','Prenume 276','2','Informatica - linia de studiu romana','3','231       ','8,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 277','Prenume 277','2','Informatica - linia de studiu romana','1','217       ','9,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 278','Prenume 278','2','Informatica - linia de studiu romana','2','221       ','8,13');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 279','Prenume 279','2','Informatica - linia de studiu romana','1','218       ','8,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 280','Prenume 280','22','Informatica - în limba engleza','4','941       ','7,9');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 281','Prenume 281','22','Informatica - în limba engleza','4','941       ','7,72');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 282','Prenume 282','22','Informatica - în limba engleza','4','942       ','6,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 283','Prenume 283','22','Informatica - în limba engleza','3','931       ','6,15');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 284','Prenume 284','22','Informatica - în limba engleza','3','931       ','5,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 285','Prenume 285','22','Informatica - în limba engleza','1','911       ','5,16');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 286','Prenume 286','22','Informatica - în limba engleza','1','911       ','6,05');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 287','Prenume 287','22','Informatica - în limba engleza','1','911       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 288','Prenume 288','22','Informatica - în limba engleza','1','911       ','5,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 289','Prenume 289','22','Informatica - în limba engleza','1','911       ','9,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 290','Prenume 290','22','Informatica - în limba engleza','1','912       ','7,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 291','Prenume 291','13','Matematica-Informatica - linia de studiu maghiara','4','641       ','7,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 292','Prenume 292','2','Informatica - linia de studiu romana','1','213       ','7,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 293','Prenume 293','2','Informatica - linia de studiu romana','1','213       ','8,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 294','Prenume 294','2','Informatica - linia de studiu romana','1','214       ','6,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 295','Prenume 295','2','Informatica - linia de studiu romana','1','214       ','6,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 296','Prenume 296','2','Informatica - linia de studiu romana','1','215       ','8,2');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 297','Prenume 297','2','Informatica - linia de studiu romana','1','216       ','7,95');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 298','Prenume 298','2','Informatica - linia de studiu romana','1','216       ','9,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 299','Prenume 299','22','Informatica - în limba engleza','3','933       ','7,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 300','Prenume 300','22','Informatica - în limba engleza','3','931       ','6,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 301','Prenume 301','3','Matematica-Informatica - linia de studiu romana','4','341       ','8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 302','Prenume 302','3','Matematica-Informatica - linia de studiu romana','4','341       ','9,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 303','Prenume 303','22','Informatica - în limba engleza','1','913       ','6,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 304','Prenume 304','22','Informatica - în limba engleza','1','914       ','7,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 305','Prenume 305','12','Informatica - linia de studiu maghiara','1','512       ','5,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 306','Prenume 306','2','Informatica - linia de studiu romana','4','243       ','5,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 307','Prenume 307','13','Matematica-Informatica - linia de studiu maghiara','3','631       ','6,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 308','Prenume 308','12','Informatica - linia de studiu maghiara','4','541       ','9,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 309','Prenume 309','3','Matematica-Informatica - linia de studiu romana','4','342       ','6,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 310','Prenume 310','2','Informatica - linia de studiu romana','4','242       ','8,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 311','Prenume 311','22','Informatica - în limba engleza','2','923       ','6,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 312','Prenume 312','2','Informatica - linia de studiu romana','3','233       ','5,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 313','Prenume 313','12','Informatica - linia de studiu maghiara','3','531       ','5,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 314','Prenume 314','12','Informatica - linia de studiu maghiara','2','521       ','7,42');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 315','Prenume 315','2','Informatica - linia de studiu romana','4','244       ','8,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 316','Prenume 316','2','Informatica - linia de studiu romana','1','211       ','6,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 317','Prenume 317','2','Informatica - linia de studiu romana','1','211       ','9,76');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 318','Prenume 318','2','Informatica - linia de studiu romana','1','211       ','5,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 319','Prenume 319','2','Informatica - linia de studiu romana','3','231       ','8,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 320','Prenume 320','2','Informatica - linia de studiu romana','2','221       ','7,91');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 321','Prenume 321','2','Informatica - linia de studiu romana','2','221       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 322','Prenume 322','22','Informatica - în limba engleza','1','914       ','9,17');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 323','Prenume 323','22','Informatica - în limba engleza','1','914       ','7,44');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 324','Prenume 324','22','Informatica - în limba engleza','1','914       ','6,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 325','Prenume 325','22','Informatica - în limba engleza','1','915       ','9,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 326','Prenume 326','22','Informatica - în limba engleza','1','915       ','9,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 327','Prenume 327','2','Informatica - linia de studiu romana','4','241       ','5,62');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 328','Prenume 328','1','Matematica - linia de studiu romana','3','131       ','9,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 329','Prenume 329','1','Matematica - linia de studiu romana','1','111       ','9,16');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 330','Prenume 330','2','Informatica - linia de studiu romana','4','244       ','5,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 331','Prenume 331','22','Informatica - în limba engleza','2','922       ','5,31');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 332','Prenume 332','2','Informatica - linia de studiu romana','1','218       ','7,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 333','Prenume 333','22','Informatica - în limba engleza','2','922       ','7,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 334','Prenume 334','22','Informatica - în limba engleza','2','922       ','9,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 335','Prenume 335','13','Matematica-Informatica - linia de studiu maghiara','2','621       ','5,27');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 336','Prenume 336','48','Optimizarea modelelor informatice','1','257       ','7,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 337','Prenume 337','3','Matematica-Informatica - linia de studiu romana','1','311       ','7,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 338','Prenume 338','2','Informatica - linia de studiu romana','1','217       ','7,92');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 339','Prenume 339','22','Informatica - în limba engleza','2','922       ','9,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 340','Prenume 340','2','Informatica - linia de studiu romana','2','221       ','6,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 341','Prenume 341','2','Informatica - linia de studiu romana','2','224       ','9,59');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 342','Prenume 342','22','Informatica - în limba engleza','4','941       ','8,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 343','Prenume 343','22','Informatica - în limba engleza','4','943       ','6,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 344','Prenume 344','22','Informatica - în limba engleza','4','942       ','5,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 345','Prenume 345','22','Informatica - în limba engleza','3','931       ','5,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 346','Prenume 346','22','Informatica - în limba engleza','3','932       ','6,81');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 347','Prenume 347','22','Informatica - în limba engleza','3','932       ','8,43');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 348','Prenume 348','22','Informatica - în limba engleza','1','911       ','8,69');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 349','Prenume 349','22','Informatica - în limba engleza','1','911       ','6,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 350','Prenume 350','22','Informatica - în limba engleza','1','912       ','9,52');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 351','Prenume 351','2','Informatica - linia de studiu romana','1','214       ','6,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 352','Prenume 352','2','Informatica - linia de studiu romana','1','215       ','8,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 353','Prenume 353','2','Informatica - linia de studiu romana','1','216       ','9,1');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 354','Prenume 354','2','Informatica - linia de studiu romana','1','217       ','5,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 355','Prenume 355','22','Informatica - în limba engleza','3','931       ','8,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 356','Prenume 356','22','Informatica - în limba engleza','3','931       ','7,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 357','Prenume 357','22','Informatica - în limba engleza','3','931       ','8,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 358','Prenume 358','22','Informatica - în limba engleza','3','932       ','7,01');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 359','Prenume 359','3','Matematica-Informatica - linia de studiu romana','4','341       ','6,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 360','Prenume 360','11','Matematica - linia de studiu maghiara','3','431       ','9,24');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 361','Prenume 361','22','Informatica - în limba engleza','1','913       ','5,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 362','Prenume 362','22','Informatica - în limba engleza','1','913       ','7,07');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 363','Prenume 363','22','Informatica - în limba engleza','1','913       ','6,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 364','Prenume 364','12','Informatica - linia de studiu maghiara','1','513       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 365','Prenume 365','12','Informatica - linia de studiu maghiara','1','511       ','8,47');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 366','Prenume 366','12','Informatica - linia de studiu maghiara','1','511       ','7,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 367','Prenume 367','12','Informatica - linia de studiu maghiara','1','511       ','8,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 368','Prenume 368','12','Informatica - linia de studiu maghiara','1','511       ','8,53');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 369','Prenume 369','12','Informatica - linia de studiu maghiara','4','541       ','5,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 370','Prenume 370','3','Matematica-Informatica - linia de studiu romana','3','331       ','7,93');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 371','Prenume 371','3','Matematica-Informatica - linia de studiu romana','3','331       ','8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 372','Prenume 372','3','Matematica-Informatica - linia de studiu romana','3','331       ','9,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 373','Prenume 373','22','Informatica - în limba engleza','1','913       ','8,66');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 374','Prenume 374','22','Informatica - în limba engleza','2','923       ','9,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 375','Prenume 375','22','Informatica - în limba engleza','2','923       ','8,49');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 376','Prenume 376','12','Informatica - linia de studiu maghiara','3','531       ','5,39');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 377','Prenume 377','12','Informatica - linia de studiu maghiara','3','531       ','5,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 378','Prenume 378','12','Informatica - linia de studiu maghiara','2','521       ','5,87');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 379','Prenume 379','2','Informatica - linia de studiu romana','1','211       ','5,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 380','Prenume 380','2','Informatica - linia de studiu romana','1','212       ','5,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 381','Prenume 381','2','Informatica - linia de studiu romana','1','212       ','8,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 382','Prenume 382','2','Informatica - linia de studiu romana','3','231       ','6,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 383','Prenume 383','2','Informatica - linia de studiu romana','3','231       ','7,36');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 384','Prenume 384','2','Informatica - linia de studiu romana','3','231       ','8,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 385','Prenume 385','2','Informatica - linia de studiu romana','3','231       ','5,26');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 386','Prenume 386','2','Informatica - linia de studiu romana','3','231       ','8,7');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 387','Prenume 387','22','Informatica - în limba engleza','1','915       ','9,55');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 388','Prenume 388','1','Matematica - linia de studiu romana','1','111       ','6,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 389','Prenume 389','2','Informatica - linia de studiu romana','4','242       ','6,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 390','Prenume 390','22','Informatica - în limba engleza','2','922       ','6,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 391','Prenume 391','22','Informatica - în limba engleza','2','921       ','7,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 392','Prenume 392','3','Matematica-Informatica - linia de studiu romana','2','321       ','8,5');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 393','Prenume 393','3','Matematica-Informatica - linia de studiu romana','2','321       ','9,99');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 394','Prenume 394','47','Modelare si simulare','1','256       ','5,64');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 395','Prenume 395','2','Informatica - linia de studiu romana','2','221       ','5,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 396','Prenume 396','2','Informatica - linia de studiu romana','2','222       ','8,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 397','Prenume 397','2','Informatica - linia de studiu romana','2','222       ','5,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 398','Prenume 398','2','Informatica - linia de studiu romana','2','221       ','5,06');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 399','Prenume 399','2','Informatica - linia de studiu romana','2','224       ','9,12');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 400','Prenume 400','22','Informatica - în limba engleza','4','941       ','5,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 401','Prenume 401','22','Informatica - în limba engleza','4','941       ','9,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 402','Prenume 402','22','Informatica - în limba engleza','4','943       ','6,44');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 403','Prenume 403','22','Informatica - în limba engleza','4','943       ','8,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 404','Prenume 404','22','Informatica - în limba engleza','4','943       ','5,37');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 405','Prenume 405','22','Informatica - în limba engleza','3','931       ','9,35');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 406','Prenume 406','22','Informatica - în limba engleza','3','932       ','9,6');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 407','Prenume 407','22','Informatica - în limba engleza','3','932       ','8,65');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 408','Prenume 408','22','Informatica - în limba engleza','3','932       ','5,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 409','Prenume 409','22','Informatica - în limba engleza','2','922       ','5,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 410','Prenume 410','22','Informatica - în limba engleza','1','911       ','8,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 411','Prenume 411','22','Informatica - în limba engleza','1','911       ','7,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 412','Prenume 412','22','Informatica - în limba engleza','1','911       ','7,29');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 413','Prenume 413','22','Informatica - în limba engleza','1','911       ','8,74');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 414','Prenume 414','22','Informatica - în limba engleza','1','912       ','8,83');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 415','Prenume 415','2','Informatica - linia de studiu romana','1','213       ','7,5');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 416','Prenume 416','2','Informatica - linia de studiu romana','1','213       ','6,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 417','Prenume 417','2','Informatica - linia de studiu romana','1','216       ','5,78');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 418','Prenume 418','2','Informatica - linia de studiu romana','1','217       ','6,08');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 419','Prenume 419','22','Informatica - în limba engleza','3','933       ','5,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 420','Prenume 420','22','Informatica - în limba engleza','3','933       ','5,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 421','Prenume 421','22','Informatica - în limba engleza','3','932       ','8,82');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 422','Prenume 422','3','Matematica-Informatica - linia de studiu romana','4','341       ','5,58');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 423','Prenume 423','3','Matematica-Informatica - linia de studiu romana','4','341       ','7,03');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 424','Prenume 424','22','Informatica - în limba engleza','1','913       ','5,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 425','Prenume 425','22','Informatica - în limba engleza','1','914       ','8,56');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 426','Prenume 426','12','Informatica - linia de studiu maghiara','1','512       ','8,94');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 427','Prenume 427','2','Informatica - linia de studiu romana','4','241       ','7,41');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 428','Prenume 428','13','Matematica-Informatica - linia de studiu maghiara','2','621       ','8,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 429','Prenume 429','12','Informatica - linia de studiu maghiara','4','541       ','9,88');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 430','Prenume 430','5','Matematici aplicate','2','122       ','7,61');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 431','Prenume 431','3','Matematica-Informatica - linia de studiu romana','4','342       ','5,8');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 432','Prenume 432','2','Informatica - linia de studiu romana','3','232       ','5,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 433','Prenume 433','3','Matematica-Informatica - linia de studiu romana','4','342       ','7,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 434','Prenume 434','22','Informatica - în limba engleza','2','923       ','8,4');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 435','Prenume 435','22','Informatica - în limba engleza','2','923       ','6,11');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 436','Prenume 436','2','Informatica - linia de studiu romana','3','233       ','7,97');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 437','Prenume 437','2','Informatica - linia de studiu romana','3','233       ','6,33');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 438','Prenume 438','12','Informatica - linia de studiu maghiara','3','531       ','6,02');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 439','Prenume 439','12','Informatica - linia de studiu maghiara','2','521       ','8,34');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 440','Prenume 440','12','Informatica - linia de studiu maghiara','2','521       ','6,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 441','Prenume 441','12','Informatica - linia de studiu maghiara','2','521       ','7,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 442','Prenume 442','2','Informatica - linia de studiu romana','1','211       ','7,32');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 443','Prenume 443','3','Matematica-Informatica - linia de studiu romana','1','311       ','8,63');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 444','Prenume 444','2','Informatica - linia de studiu romana','3','232       ','5,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 445','Prenume 445','22','Informatica - în limba engleza','1','914       ','5,57');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 446','Prenume 446','22','Informatica - în limba engleza','1','914       ','9,54');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 447','Prenume 447','22','Informatica - în limba engleza','1','915       ','9,68');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 448','Prenume 448','22','Informatica - în limba engleza','1','915       ','5,77');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 449','Prenume 449','12','Informatica - linia de studiu maghiara','1','513       ','6,71');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 450','Prenume 450','22','Informatica - în limba engleza','1','915       ','6,51');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 451','Prenume 451','2','Informatica - linia de studiu romana','4','241       ','8,46');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 452','Prenume 452','2','Informatica - linia de studiu romana','4','244       ','9,04');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 453','Prenume 453','43','Baze de date','1','253       ','5,64');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 454','Prenume 454','22','Informatica - în limba engleza','2','921       ','6,14');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 455','Prenume 455','22','Informatica - în limba engleza','2','921       ','5,73');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 456','Prenume 456','3','Matematica-Informatica - linia de studiu romana','2','321       ','8,3');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 457','Prenume 457','2','Informatica - linia de studiu romana','2','223       ','5,38');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 458','Prenume 458','3','Matematica-Informatica - linia de studiu romana','2','321       ','5,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 459','Prenume 459','2','Informatica - linia de studiu romana','4','243       ','9,25');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 460','Prenume 460','2','Informatica - linia de studiu romana','2','222       ','9,23');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 461','Prenume 461','22','Informatica - în limba engleza','2','922       ','7,21');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 462','Prenume 462','22','Informatica - în limba engleza','4','943       ','9,45');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 463','Prenume 463','22','Informatica - în limba engleza','4','942       ','5,78');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 464','Prenume 464','22','Informatica - în limba engleza','1','914       ','8,19');
Insert into STUDENTI (NUME,PRENUME,COD_SECTIA,DENUMIRE_SECTIA,AN_STUDIU,GRUPA,MEDIA) values ('Nume 465','Prenume 465','2','Informatica - linia de studiu romana','4','243       ','7,14');